// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDoBzdX1KzLYmMsnFnAQuBMh648M_MW-c',
    appId: '1:966690184394:web:1f3130d52cdbece896a833',
    messagingSenderId: '966690184394',
    projectId: 'ztdip-2a11c',
    authDomain: 'ztdip-2a11c.firebaseapp.com',
    storageBucket: 'ztdip-2a11c.appspot.com',
    measurementId: 'G-MW0SX3EY0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_LkySAItojMoqYBiBONQ8g2o3GymSfBc',
    appId: '1:966690184394:android:679487e7b553bfe496a833',
    messagingSenderId: '966690184394',
    projectId: 'ztdip-2a11c',
    storageBucket: 'ztdip-2a11c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj0yxnINA8aXpfYfv71IGHC2JRb6pxdbY',
    appId: '1:966690184394:ios:bd459e5755ccc97d96a833',
    messagingSenderId: '966690184394',
    projectId: 'ztdip-2a11c',
    storageBucket: 'ztdip-2a11c.appspot.com',
    iosClientId: '966690184394-0hurc2i4udkcmq6u86elckd84b0ajr24.apps.googleusercontent.com',
    iosBundleId: 'com.example.grageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj0yxnINA8aXpfYfv71IGHC2JRb6pxdbY',
    appId: '1:966690184394:ios:bd459e5755ccc97d96a833',
    messagingSenderId: '966690184394',
    projectId: 'ztdip-2a11c',
    storageBucket: 'ztdip-2a11c.appspot.com',
    iosClientId: '966690184394-0hurc2i4udkcmq6u86elckd84b0ajr24.apps.googleusercontent.com',
    iosBundleId: 'com.example.grageApp',
  );
}
